### ISSUE TITLE
How to achieve this

### ISSUE THREAD

**Issue by adeleglise** [atidyshirt/MacOS-Dotfiles#4] opened 2020-07-11 09:12 UTC
Hi, first of all thanks a lot for sharing your ricing.

However, I'm kinda new to the MacOS ricing world (coming from Linux ricing).  I think i'm missing a lot of things just to be able to reproduce your configuration.

- Which ubersicht widgets should I install ?
- Should I hide the bottom bar ?
- All of the pywal an .Xresources seems to be Linux like, but I can't get them to load
- Neovim is asking for nodejs ???

**Comment by atidyshirt** [comment] 2020-07-11 14:50
ok, there seems to be a few issues here, the installer has been updated as per @WarpWing changes. when using the installer, it should install my fork of the simple-bar widget (you will possibly need to manually load this, ie load simple-bar process, data and spaces widget. Neovim will ask you to install Nodejs, as it uses it for some of the packages ie coc.nvim, if you install from my script, the way to load pywal colors will be with the 'wall ~/image' command, as it needs to use the walset.sh script in order to load all of the necessary files, and set the xresources. Hopefully this helps, feel free to ask if you need more info :)

**Comment by WarpWing** [comment] 2020-07-11 15:39
> ok, there seems to be a few issues here, the installer has been updated as per @WarpWing changes. when using the installer, it should install my fork of the simple-bar widget (you will possibly need to manually load this, ie load simple-bar process, data and spaces widget. Neovim will ask you to install Nodejs, as it uses it for some of the packages ie coc.nvim, if you install from my script, the way to load pywal colors will be with the 'wall ~/image' command, as it needs to use the walset.sh script in order to load all of the necessary files, and set the xresources. Hopefully this helps, feel free to ask if you need more info :)

I should also note that your version of simple-bar gives a error on install. There is no issues tab of your version of simple-bar for me so I believe it's better for me to post it here. I recommend going with 

https://github.com/Jean-Tinland/simple-bar

For now imo. 

For @atidyshirt  

Here is the error message I got on install  
![Screen Shot 2020-07-10 at 12 56 09 PM](https://user-images.githubusercontent.com/28925758/87227810-3bc67400-c36b-11ea-816f-d227488c7bbe.png)

Expect a pull req from me soon <3

**Comment by WarpWing** [comment] 2020-07-11 16:06
> Hi, first of all thanks a lot for sharing your ricing.
> 
> However, I'm kinda new to the MacOS ricing world (coming from Linux ricing). I think i'm missing a lot of things just to be able to reproduce your configuration.
> 
> * Which ubersicht widgets should I install ?
> * Should I hide the bottom bar ?
> * All of the pywal an .Xresources seems to be Linux like, but I can't get them to load
> * Neovim is asking for nodejs ???

In response to your query (I am not Jordan but I hope my two cents will help)

Q: Which ubersicht widgets should I install ? 
A: You don't need to reproduce Jordan's configuration. He has the dotfiles and a pretty good working install script. You can just clone the repository and run the script.

Q: Should I hide the bottom bar ?
A: That is completely up to you. You don't need to clone Jordan's config completely. The style of your rice is completely up to you. If you want to reproduce Jordan's configuration exactly, you shoud hide the bottom bar

Q: Neovim is asking for nodejs ???
A: I suppose it needs node.js so I suspect you need to install it

Q: All of the pywal an .Xresources seems to be Linux like, but I can't get them to load
A: I think @atidyshirt  should answer this lmao. This is a bit out of my territory

**Comment by WarpWing** [comment] 2020-07-11 23:24
Little Update: congrats to @adeleglise on opening his first issue :)

**Comment by WarpWing** [comment] 2020-07-12 03:37
Should you close this @atidyshirt  ?

**Comment by adeleglise** [comment] 2020-07-13 08:22
Hi, sorry guys for the delay. Thanks a lot for all your answers. I will try to apply it and get back to you.

**Comment by WarpWing** [comment] 2020-07-13 13:09
> Hi, sorry guys for the delay. Thanks a lot for all your answers. I will try to apply it and get back to you.

Take ur time. Jordan and I are happy to help to help :D

**Closed as completed** 2020-07-22 06:18 UTC
Labels: question
